project:
  output-dir: _output

bibliography: msens.bib
bibliographystyle: apa

format:
  html:
    toc: true
    number-sections: true
    code-fold: true
    code-tools: true
    standalone: false
    embed-resources: false

search: false
